{
 "title": "CloudWatch Exporter",
 "description": "Dashboard for Amazon CloudWatch exporter with prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "EC2",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "EKS",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 0 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "ELB",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "CPU Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "round(aws_ec2_cpuutilization_average offset 10m, 0.01)"
    },
    {}
   ]
  },
  {
   "title": "Node CPU Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "round(containerinsights_node_cpu_utilization_average offset 10m,0.01)"
    }
   ]
  },
  {
   "title": "ELB Down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "aws_elb_un_healthy_host_count_average offset 10m"
    }
   ]
  },
  {
   "title": "MEM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "round(cwagent_mem_used_percent_average offset 10m,0.01)"
    }
   ]
  },
  {
   "title": "Node MEM Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "round(containerinsights_node_memory_utilization_average offset 10m,0.01)"
    }
   ]
  },
  {
   "title": "Surge Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "aws_elb_surge_queue_length_average"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "round(cwagent_disk_used_percent_average offset 10m,0.01)"
    }
   ]
  },
  {
   "title": "Node Filesystem Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "round(containerinsights_node_filesystem_utilization_average offset 10m,0.01)"
    }
   ]
  },
  {
   "title": "Pod CPU Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "round(containerinsights_pod_cpu_utilization_average offset 10m,0.01)"
    }
   ]
  },
  {
   "title": "Pod MEM Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "round(containerinsights_pod_memory_utilization_average offset 10m,0.01)"
    }
   ]
  }
 ]
}